var = "Hello Bangladesh cleavercode"
# print(len(var))
# print(var[::])
# print(var.count('l'))
print(var.capitalize())
print(var.find('cleavercode'))
print(var.upper())
print(var.lower())
print(var.replace('cleavercode','subscribe to cleavercode'))
print(var.endswith('cleavercode'))